miss_penalty = 100
pipelining = false
volatile_penalty = 20
writethrough = false

[cache.data]
mode = "associative"
offset_bits = 2
set_bits = 2
ways = 2

[cache.instruction]
mode = "associative"
offset_bits = 6
set_bits = 2
ways = 2
