[package]
name = "seis-asm"
version = "0.1.0"
edition = "2021"
authors = ["Francisco Santana"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.libasm]
path = "../libasm/"

[dependencies.clap]
version = "4.5.2"
features = ["derive"]
